export const After2 = '::after';
export const Backdrop = '::backdrop';
export const Before2 = '::before';
export const Colon2 = '::cue';
export const FirstLetter2 = '::first-letter';
export const FirstLine2 = '::first-line';
export const GrammarError = '::grammar-error';
export const Placeholder = '::placeholder';
export const Selection = '::selection';
export const Slotted2 = '::slotted';
export const SpellingError = '::spelling-error';
export const Active = ':active';
export const After = ':after';
export const AnyLink = ':any-link';
export const Before = ':before';
export const Blank = ':blank';
export const Checked = ':checked';
export const Default = ':default';
export const Defined = ':defined';
export const Disabled = ':disabled';
export const Empty = ':empty';
export const Enabled = ':enabled';
export const First = ':first';
export const FirstChild = ':first-child';
export const FirstLetter = ':first-letter';
export const FirstLine = ':first-line';
export const FirstOfType = ':first-of-type';
export const Focus = ':focus';
export const FocusWithin = ':focus-within';
export const Fullscreen = ':fullscreen';
export const Hover = ':hover';
export const InRange = ':in-range';
export const Indeterminate = ':indeterminate';
export const Invalid = ':invalid';
export const LastChild = ':last-child';
export const LastOfType = ':last-of-type';
export const Left = ':left';
export const Link = ':link';
export const OnlyChild = ':only-child';
export const OnlyOfType = ':only-of-type';
export const Optional = ':optional';
export const OutOfRange = ':out-of-range';
export const PlaceholderShown = ':placeholder-shown';
export const ReadOnly = ':read-only';
export const ReadWrite = ':read-write';
export const Required = ':required';
export const Right = ':right';
export const Root = ':root';
export const Scope = ':scope';
export const Target = ':target';
export const Valid = ':valid';
export const Visited = ':visited';

// Dynamic pseudo selectors
export const Dir = (dir: 'ltr' | 'rtl') => `:dir(${dir})`;
export const Has = (selector: string) => `:has(${selector})`;
export const Host = (selector: string) => `:host(${selector})`;
export const HostContext = (selector: string) => `:host-context(${selector})`;
export const Is = (selector: string) => `:is(${selector})`;
export const Lang = (language: string) => `:lang(${language})`;
export const Not = (selector: string) => `:not(${selector})`;
export const NthChild = (n: number) => `:nth-child${n}`;
export const NthLastChild = (n: number) => `:nth-last-child(${n})`;
export const NthLastOfType = (n: number) => `:nth-last-of-type(${n})`;
export const NthOfType = (n: number) => `:nth-of-type(${n})`;
export const Where = (selector: string) => `:where(${selector})`;
